### ISSUE TITLE
Pull requests from forks will not build correctly

### ISSUE THREAD

**Issue by nolman** [square/kochiku#11]
Kochiku workers have been updated to support this however I am 99% certian that the mainline repository does not enqueue a job with the correct (ie the fork) repository url.

I have a [branch](https://github.com/square/kochiku/compare/building-forks) that starts to add support for this however I haven't had a chance to finish it, wanted to make an issue to record this problem for the public.

**Comment by robolson** [comment]
Fixed by #200 
Fixed by #261 
Fixed by https://github.com/square/kochiku-worker/pull/55

Your welcome @nolman!

**Comment by nolman** [comment]
Thanks @robolson!
