### ISSUE TITLE
Merge on Success uses Kochiku Robot as the author

### ISSUE THREAD

**Issue by ryho** [square/kochiku#259]
Merge on Success uses Kochiku Robot as the author for the merge commit, it should use the author from the commits that it is merging in.
Since it shows that the author of the merge is Kochiku Robot, a lot of git tools like git blame and IntelliJ's Annotate Lines become much less useful when your team members are using Merge on Success:
![screen shot 2017-10-02 at 2 52 57 pm](https://user-images.githubusercontent.com/2478057/31450600-d528997c-ae77-11e7-9808-19b18ee9ba4e.png)
This should be pretty simple to solve, git authors can be set to whatever you like with the flag `--author="John Doe <john@doe.org>"` in most git commands.

**Comment by robolson** [comment]
Kochiku appears to do this correctly already. I believe this was the result of an unusual merge or a developer amended a merge commit. Not entirely sure but it doesn't happen normally.
